Fix warning about unused variable
assimpimporter.cpp:616:75: error: unused parameter ‘basePath’ [-Werror=unused-parameter]

Change-Id: I8d96dea9955d4c749b99fffd14cd62dd3d0fa45f
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>