Remove AUTOTEST_EXPORT from templated function
...to avoid warnings (that can be treated as errors) with Mingw.

What we have seen in the CI is that including renderer_p.h from an
external module can lead to

error: inline function 'T Qt3DRender::Render::variant_value(const
QVariant&)' declared as  dllimport: attribute ignored [-Werror=attributes]
Q_AUTOTEST_EXPORT inline T variant_value(const QVariant &v)

which is treated as an error if the external user happens to be a Qt
module with warning_clean enabled.

Not sure why this surfaced now, but removing the export should be the
correct thing to do regardless.

Change-Id: Ie8de120fa0e5c96fbcffc1632db57edeac87a95b
Reviewed-by: Christian Stromme <christian.stromme@qt.io>