Silence ICC warning about unused local variable
 quick3dshaderdata.cpp(56): error #2415: variable "Qt3DRender::Render::Quick::<unnamed>::quick3DShaderDataTypeId" of static storage duration was declared but never referenced

Since the initialization has side effects, we need to keep the
variable, so just mark it unuse.

Change-Id: I27b55fdf514247549455fffd14b1c9712ac05281
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>