QSortPolicy: fix argument passing
Pass containers by reference to const, not by value.

Exception: setSortTypes(QVector<SortType>), because that
unconditionally stores the argument in a member variable.
Add std::move() there.

Saves ~0.5KiB in libQt53DRender text size on optimized
GCC 6.0 Linux AMD64 builds.

Change-Id: Ie48b80cd42973e69807f7832598cf15ffde25cc8
Reviewed-by: Volker Krause <volker.krause@kdab.com>