Remove the << version of qCWarning from headers
This triggers warnings in pedantic compilation mode since passing zero
arguments to the ... is not permitted.

GCC:   quniformvalue.h:188:38: error: ISO C99 requires rest arguments to be used
Clang: quniformvalue.h:141:38: error: must specify at least one argument for '...' parameter of variadic macro [-Werror,-Wgnu-zero-variadic-macro-arguments]

This commit also removes the Q_FUNC_INFO, which isn't necessary. If the
user wants it, they can set QT_MESSAGE_PATTERN in the environment.

Discussed-on: http://lists.qt-project.org/pipermail/development/2014-August/018022.html
Change-Id: Ic75c669f2b5364033d8987f130b5d24a5cf80454
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>
Reviewed-by: Sean Harmer <sean.harmer@kdab.com>