Fix build: src/plugins/sceneparsers/assimp depends on Qt3DAnimation
 /usr/bin/ld.gold: error: cannot find -lQt53DAnimation
 assimpimporter.o:assimpimporter.cpp:function Qt3DRender::AssimpImporter::node(aiNode*): error:
 undefined reference to 'Qt3DAnimation::QKeyframeAnimation::setTarget(Qt3DCore::QTransform*)'

Change-Id: I84e45059a888497fb55ffffd14d2e19ea52ecf55
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>