Initialize the unused member
GCC 7 complains that it is used uninitialized. The line number points to
the opening brace of the class, so I suppose it's the implicit copy
constructor.

Loading undefined floating point values is probably a bad idea. Could
generate an FP exception.

animationutils_p.h:126:8: error: ‘<anonymous>.Qt3DAnimation::Animation::ChannelNameAndType::pad’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

Change-Id: I11d489f37e7e424b971dfffd150e3268d4be9294
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>