QGeometryFactory: don't make op== virtual
That's too clever, and it backfires with compilation errors in C++20
mode:

  qt3d/tests/auto/render/meshfunctors/tst_meshfunctors.cpp:129:29: error: ambiguous overload for ‘operator==’ (operand types are ‘MeshFunctorA’ and ‘MeshFunctorB’)
    129 |         QVERIFY(!(*functorA == *functorB));
        |                   ~~~~~~~~~ ^~ ~~~~~~~~~
        |                   |            |
        |                   MeshFunctorA MeshFunctorB
  qt3d/tests/auto/render/meshfunctors/tst_meshfunctors.cpp:72:10: note: candidate: ‘virtual bool MeshFunctorB::operator==(const Qt3DCore::QGeometryFactory&) const’ (reversed)
     72 |     bool operator ==(const Qt3DCore::QGeometryFactory &other) const override
        |          ^~~~~~~~
  qt3d/tests/auto/render/meshfunctors/tst_meshfunctors.cpp:50:10: note: candidate: ‘virtual bool MeshFunctorA::operator==(const Qt3DCore::QGeometryFactory&) const’
     50 |     bool operator ==(const Qt3DCore::QGeometryFactory &other) const override
        |          ^~~~~~~~

Fix by providing a symmetric operator== for QGeometryFactory that
delegates to a virtual equals() method.

Change-Id: I23d29ad1b16075629132f2b4757c5810d5615a36
Reviewed-by: Edward Welbourne <edward.welbourne@qt.io>
Reviewed-by: Paul Lemire <paul.lemire@kdab.com>
(cherry picked from commit ec291f9974ba6d25148955a0b9e55b30c589a9be)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>