Fix build errors on OS X 10.8
error: no member named 'srand' in namespace 'std' when <cstdlib> is not
included.

Using int instead of bool in tst_raycasting

Change-Id: I03bc669a2a3683376523a25e854e485c6ba0e0c5
Reviewed-by: Laszlo Agocs <laszlo.agocs@theqtcompany.com>